name: (E2E Tests) Meshery Adapter for Linkerd Tests

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
    paths-ignore:
      - 'docs/**'   
  pull_request:
     branches:
       - "*"
  release:
    types: [published]
jobs:
  SetPatternfile:
    runs-on: ubuntu-latest
    outputs:
      sm_version: ${{ steps.gettag.outputs.release }}
      adapter_version:  ${{ env.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Get latest release tag
        id: gettag
        run: |
           NEW_LINKERD_VERSION=$(curl --silent "https://api.github.com/repos/linkerd/linkerd2/releases" | jq ' .[] | select(.tag_name|test("stable")) | ."tag_name"' | sed -n 1p$'\n' | tr -d '"')
           echo "::set-output name=release::$NEW_LINKERD_VERSION"
      - name: Get stable release version
        id: getstabletag
        run: |
          if [ ${{ github.event_name }} == "release" ]; then
            echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          else
            echo "version=edge" >> $GITHUB_ENV
          fi
      - name: Change service mesh version in patternfile
        run: | 
           yq e -i '.services.linkerd.version="${{ steps.gettag.outputs.release }}"' ./.github/install/deploy.yaml 
           cat ./.github/install/deploy.yaml
      - name: Uploading file
        uses: actions/upload-artifact@v4
        with:
          name: patternfile
          path: ./.github/install/deploy.yaml
          overwrite: true

  TestLinkerd:
    needs: SetPatternfile
    uses: meshery/meshery/.github/workflows/test_adaptersv2.yaml@master
    with:
      expected_resources: linkerd-destination,linkerd-identity,linkerd-proxy-injector
      expected_resources_types: pod,pod,pod
      expected_resources_namespaces: linkerd-system,linkerd-system,linkerd-system
      deployment_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-linkerd-deployment.yaml
      service_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-linkerd-service.yaml
      adapter_name: linkerd
      patternfile_name: deploy.yaml
      provider: Local
      k8s_version: v1.22.15
      sm_version: ${{ needs.SetPatternfile.outputs.sm_version }}
      adapter_version:  ${{ needs.SetPatternfile.outputs.adapter_version }}
      output_filename: data.json
    secrets:
      token: ${{ secrets.PROVIDER_TOKEN }} 


  UpdateDocs:
    needs: TestLinkerd
    if:  "always() && github.event_name != 'pull_request' "
    runs-on: ubuntu-latest
    steps:
      - name: Skip if needed
        run: |
            echo "this is it ${{ needs.SkipIfNeeded.outputs.skipdocupdate }} "
            if [ "${{github.event_name }}" == "push" ];then
              echo "version=edge" >> $GITHUB_ENV
            fi
            if [ "${{github.event_name }}" == "release" ];then
              echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
            fi
      - uses: actions/checkout@master
        with:
          repository: meshery/meshery 
          token: ${{ secrets.GH_ACCESS_TOKEN }}   
      - name: DownloadJSON
        uses: actions/download-artifact@v4
        with:
          name: data.json
      - name: echo results
        run: |
          pretty=$(jq . data.json)
          rm data.json
          mkdir -p ./docs/_compatibility/meshery-linkerd
          cd ./docs/_compatibility/meshery-linkerd
          touch data.json
          echo $pretty > data.json
          cat data.json
          touch test.md
          filename=(`date +%m-%d-%Y-%H-%M-%m_${SHORT_SHA}`)
          echo $filename
          echo "---
          timestamp: $(jq '.metadata.runon| strptime("%a %b %e %X %Z %Y") | strftime("%Y-%m-%d %X %Z %a")' data.json)
          meshery-component: meshery-linkerd
          meshery-component-version: $version
          meshery-server-version: $(jq '.metadata."meshery-server-version"' data.json)
          k8s-distro: minikube
          k8s-version: $(jq '.metadata.k8s_version' data.json)
          service-mesh: Linkerd
          service-mesh-version: $(jq '.metadata.service_mesh_version' data.json)
          tests:
            pod/linkerd-destination: $(jq '.resources_status."pod/linkerd-destination"' data.json)
            pod/linkerd-identity: $(jq '.resources_status."pod/linkerd-identity"' data.json)
            pod/linkerd-proxy-injector:  $(jq '.resources_status."pod/linkerd-proxy-injector"' data.json)
          overall-status: $(jq '."overall-status"' data.json)
          ---" >  test.md
          mv test.md $filename.md
          rm data.json
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs
          commit_user_name: l5io
          commit_user_email: ci@meshery.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: '[Docs] Test status of adapter'
